export const leadData = [
  {
    name: "Alice Smith",
    email: "alice.smith@example.com",
    phone: "555-123-1001",
    tags: ["New Customer", "Lead", "Tag1"],
  },
  {
    name: "Bob Johnson",
    email: "bob.johnson@example.com",
    phone: "555-123-1002",
    tags: ["Returning", "Tag2"],
  },
  {
    name: "Charlie Lee",
    email: "charlie.lee@example.com",
    phone: "555-123-1003",
    tags: ["Interested", "Follow-up"],
  },
  {
    name: "Diana Prince",
    email: "diana.prince@example.com",
    phone: "555-123-1004",
    tags: ["Hot Lead", "VIP"],
  },
  {
    name: "Ethan Hunt",
    email: "ethan.hunt@example.com",
    phone: "555-123-1005",
    tags: ["Cold Lead", "Tag1"],
  },
  {
    name: "Fiona Gallagher",
    email: "fiona.g@example.com",
    phone: "555-123-1006",
    tags: ["New Customer", "Promo"],
  },
  {
    name: "George Clooney",
    email: "george.c@example.com",
    phone: "555-123-1007",
    tags: ["Tag1", "VIP"],
  },
  {
    name: "Hannah Baker",
    email: "hannah.b@example.com",
    phone: "555-123-1008",
    tags: ["Follow-up"],
  },
  {
    name: "Ivan Petrov",
    email: "ivan.p@example.com",
    phone: "555-123-1009",
    tags: ["Hot Lead", "Priority"],
  },
  {
    name: "Julia Roberts",
    email: "julia.r@example.com",
    phone: "555-123-1010",
    tags: ["Returning", "Tag2"],
  },
  {
    name: "Kevin Hart",
    email: "kevin.h@example.com",
    phone: "555-123-1011",
    tags: ["New Customer"],
  },
  {
    name: "Laura Palmer",
    email: "laura.p@example.com",
    phone: "555-123-1012",
    tags: ["Cold Lead", "Inactive"],
  },
  {
    name: "Mike Ross",
    email: "mike.r@example.com",
    phone: "555-123-1013",
    tags: ["Interested"],
  },
  {
    name: "Nina Dobrev",
    email: "nina.d@example.com",
    phone: "555-123-1014",
    tags: ["Tag2", "Lead"],
  },
  {
    name: "Oscar Wilde",
    email: "oscar.w@example.com",
    phone: "555-123-1015",
    tags: ["New Customer"],
  },
  {
    name: "Pam Beesly",
    email: "pam.b@example.com",
    phone: "555-123-1016",
    tags: ["Returning", "Follow-up"],
  },
  {
    name: "Quentin Blake",
    email: "quentin.b@example.com",
    phone: "555-123-1017",
    tags: ["VIP"],
  },
  {
    name: "Rachel Green",
    email: "rachel.g@example.com",
    phone: "555-123-1018",
    tags: ["Tag1", "Hot Lead"],
  },
  {
    name: "Steve Rogers",
    email: "steve.r@example.com",
    phone: "555-123-1019",
    tags: ["Priority"],
  },
  {
    name: "Tina Fey",
    email: "tina.f@example.com",
    phone: "555-123-1020",
    tags: ["Promo", "Lead"],
  },
];
